---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
      - id: check-xml

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --extra dev mypy .
        language: system
        pass_filenames: false
        types: [python]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args:
          - -s
          - B101
        additional_dependencies:
          - pbr

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.1
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, athena, --templater, jinja, --ignore, templating]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
        args:
          - --tf-init-args=-lockfile=readonly
      - id: terraform_checkov
        args:
          - --args=--framework terraform
          - --args=--quiet
          - --args=--compact
