site_name: pipeline-builder
repo_url: https://github.com/moj-analytical-services/opg-pipeline-builder

theme:
  name: tech_docs_template
  logo: logos/moj.png
  favicon: favicons/moj.ico

nav:
  - Home: "README.md"
  - Guide:
      - Background: guide/background.md
  - API:
      - Pipeline: api/pipeline.md
      - Database: api/database.md

plugins:
  - material/search
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - mdx_include
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
