---
name: Security
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
jobs:
  security:
    name: Security
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-security.yml@867b0f83016b15386c659b6a18fbd85037eb662f # v1.0.0
